import { Router } from "express";
import { authRouter } from "./auth.routes";
import { appointmentRouter } from "./appointment.routes";
import { scheduleRouter } from "./schedule.routes";
import { serviceRouter } from "./service.routes";
import { userRouter } from "./user.routes";
import { doctorRouter } from "./doctor.routes";
import { adminRouter } from "./admin.routes";
import { waitlistRouter } from "./waitlist.routes";
import { locationRouter } from "./location.routes";
import { recallRouter } from "./recall.routes";
import { inviteRouter } from "./invite.routes";
import { publicRouter } from "./public.routes";
import { superAdminRouter } from "./superAdmin.routes";

export const router = Router();

router.use("/auth", authRouter);
router.use("/invites", inviteRouter);
router.use("/public", publicRouter);
router.use("/super-admin", superAdminRouter);
router.use("/appointments", appointmentRouter);
router.use("/schedule", scheduleRouter);
router.use("/services", serviceRouter);
router.use("/users", userRouter);
router.use("/doctors", doctorRouter);
router.use("/admin", adminRouter);
router.use("/waitlist", waitlistRouter);
router.use("/locations", locationRouter);
router.use("/recalls", recallRouter);
